//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://sms2.cdyne.com", ClrNamespace="sms2.cdyne.com")]

namespace sms2.cdyne.com
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSResponse", Namespace="http://sms2.cdyne.com")]
    public partial class SMSResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool CancelledField;
        
        private System.Guid MessageIDField;
        
        private bool QueuedField;
        
        private string ReferenceIDField;
        
        private sms2.cdyne.com.SMSErrors SMSErrorField;
        
        private sms2.cdyne.com.SMSIncomingMessage[] SMSIncomingMessagesField;
        
        private bool SentField;
        
        private System.DateTime SentDateTimeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Cancelled
        {
            get
            {
                return this.CancelledField;
            }
            set
            {
                this.CancelledField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid MessageID
        {
            get
            {
                return this.MessageIDField;
            }
            set
            {
                this.MessageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Queued
        {
            get
            {
                return this.QueuedField;
            }
            set
            {
                this.QueuedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceID
        {
            get
            {
                return this.ReferenceIDField;
            }
            set
            {
                this.ReferenceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public sms2.cdyne.com.SMSErrors SMSError
        {
            get
            {
                return this.SMSErrorField;
            }
            set
            {
                this.SMSErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sms2.cdyne.com.SMSIncomingMessage[] SMSIncomingMessages
        {
            get
            {
                return this.SMSIncomingMessagesField;
            }
            set
            {
                this.SMSIncomingMessagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Sent
        {
            get
            {
                return this.SentField;
            }
            set
            {
                this.SentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentDateTime
        {
            get
            {
                return this.SentDateTimeField;
            }
            set
            {
                this.SentDateTimeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSErrors", Namespace="http://sms2.cdyne.com")]
    public enum SMSErrors : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoError = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STOPfromPhoneNumber = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LicenseKeyInvalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhoneNumberInvalid = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageInvalid = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScheduledDateTimeIsNotUTC = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAssignedDID = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContactCdyneAccountSuspended = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSIncomingMessage", Namespace="http://sms2.cdyne.com")]
    public partial class SMSIncomingMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FromPhoneNumberField;
        
        private System.Guid IncomingMessageIDField;
        
        private System.Guid MatchedMessageIDField;
        
        private string MessageField;
        
        private System.DateTime ResponseReceiveDateField;
        
        private string ToPhoneNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromPhoneNumber
        {
            get
            {
                return this.FromPhoneNumberField;
            }
            set
            {
                this.FromPhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IncomingMessageID
        {
            get
            {
                return this.IncomingMessageIDField;
            }
            set
            {
                this.IncomingMessageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MatchedMessageID
        {
            get
            {
                return this.MatchedMessageIDField;
            }
            set
            {
                this.MatchedMessageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResponseReceiveDate
        {
            get
            {
                return this.ResponseReceiveDateField;
            }
            set
            {
                this.ResponseReceiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPhoneNumber
        {
            get
            {
                return this.ToPhoneNumberField;
            }
            set
            {
                this.ToPhoneNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSRequest", Namespace="http://sms2.cdyne.com")]
    public partial class SMSRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AssignedDIDField;
        
        private string MessageField;
        
        private string[] PhoneNumbersField;
        
        private string ReferenceIDField;
        
        private System.DateTime ScheduledDateTimeField;
        
        private string StatusPostBackURLField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AssignedDID
        {
            get
            {
                return this.AssignedDIDField;
            }
            set
            {
                this.AssignedDIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PhoneNumbers
        {
            get
            {
                return this.PhoneNumbersField;
            }
            set
            {
                this.PhoneNumbersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceID
        {
            get
            {
                return this.ReferenceIDField;
            }
            set
            {
                this.ReferenceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime ScheduledDateTime
        {
            get
            {
                return this.ScheduledDateTimeField;
            }
            set
            {
                this.ScheduledDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusPostBackURL
        {
            get
            {
                return this.StatusPostBackURLField;
            }
            set
            {
                this.StatusPostBackURLField = value;
            }
        }
    }
}
namespace SmsWS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSAdvancedRequest", Namespace="http://schemas.datacontract.org/2004/07/SmsWS")]
    public partial class SMSAdvancedRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid LicenseKeyField;
        
        private sms2.cdyne.com.SMSRequest[] SMSRequestsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LicenseKey
        {
            get
            {
                return this.LicenseKeyField;
            }
            set
            {
                this.LicenseKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sms2.cdyne.com.SMSRequest[] SMSRequests
        {
            get
            {
                return this.SMSRequestsField;
            }
            set
            {
                this.SMSRequestsField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://sms2.cdyne.com", ConfigurationName="Isms")]
public interface Isms
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/SimpleSMSsend", ReplyAction="http://sms2.cdyne.com/Isms/SimpleSMSsendResponse")]
    sms2.cdyne.com.SMSResponse SimpleSMSsend(string PhoneNumber, string Message, System.Guid LicenseKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/SimpleSMSsendWithPostback", ReplyAction="http://sms2.cdyne.com/Isms/SimpleSMSsendWithPostbackResponse")]
    sms2.cdyne.com.SMSResponse SimpleSMSsendWithPostback(string PhoneNumber, string Message, System.Guid LicenseKey, string StatusPostBackURL);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/AdvancedSMSsend", ReplyAction="http://sms2.cdyne.com/Isms/AdvancedSMSsendResponse")]
    sms2.cdyne.com.SMSResponse[] AdvancedSMSsend(SmsWS.SMSAdvancedRequest AdvancedRequest);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetMessageStatus", ReplyAction="http://sms2.cdyne.com/Isms/GetMessageStatusResponse")]
    sms2.cdyne.com.SMSResponse GetMessageStatus(System.Guid MessageID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetMessageStatusByReferenceID", ReplyAction="http://sms2.cdyne.com/Isms/GetMessageStatusByReferenceIDResponse")]
    sms2.cdyne.com.SMSResponse[] GetMessageStatusByReferenceID(string ReferenceID, System.Guid LicenseKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessages", ReplyAction="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessagesResponse")]
    sms2.cdyne.com.SMSIncomingMessage[] GetUnreadIncomingMessages(System.Guid LicenseKey);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/CancelMessage", ReplyAction="http://sms2.cdyne.com/Isms/CancelMessageResponse")]
    bool CancelMessage(System.Guid MessageID);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IsmsChannel : Isms, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class IsmsClient : System.ServiceModel.ClientBase<Isms>, Isms
{
    
    public IsmsClient()
    {
    }
    
    public IsmsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public IsmsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public IsmsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public IsmsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public sms2.cdyne.com.SMSResponse SimpleSMSsend(string PhoneNumber, string Message, System.Guid LicenseKey)
    {
        return base.Channel.SimpleSMSsend(PhoneNumber, Message, LicenseKey);
    }
    
    public sms2.cdyne.com.SMSResponse SimpleSMSsendWithPostback(string PhoneNumber, string Message, System.Guid LicenseKey, string StatusPostBackURL)
    {
        return base.Channel.SimpleSMSsendWithPostback(PhoneNumber, Message, LicenseKey, StatusPostBackURL);
    }
    
    public sms2.cdyne.com.SMSResponse[] AdvancedSMSsend(SmsWS.SMSAdvancedRequest AdvancedRequest)
    {
        return base.Channel.AdvancedSMSsend(AdvancedRequest);
    }
    
    public sms2.cdyne.com.SMSResponse GetMessageStatus(System.Guid MessageID)
    {
        return base.Channel.GetMessageStatus(MessageID);
    }
    
    public sms2.cdyne.com.SMSResponse[] GetMessageStatusByReferenceID(string ReferenceID, System.Guid LicenseKey)
    {
        return base.Channel.GetMessageStatusByReferenceID(ReferenceID, LicenseKey);
    }
    
    public sms2.cdyne.com.SMSIncomingMessage[] GetUnreadIncomingMessages(System.Guid LicenseKey)
    {
        return base.Channel.GetUnreadIncomingMessages(LicenseKey);
    }
    
    public bool CancelMessage(System.Guid MessageID)
    {
        return base.Channel.CancelMessage(MessageID);
    }
}
