//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;

namespace Org.Software.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Org_Software", "", "AppLogDetail")]
    public partial class AppLogDetail
    {
        public int LogDetailId { get; set; }
        public long LogId { get; set; }
        public string AppLogDetailTypeCode { get; set; }
        public string LogDetail { get; set; }
    
        public virtual AppLog AppLog { get; set; }
        public virtual AppLogDetailType AppLogDetailType { get; set; }
    }
}
