//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;

namespace Org.Software.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Org_Software", "", "AppLogDetailType")]
  public partial class AppLogDetailType
  {
    public AppLogDetailType()
    {
      this.AppLogDetails = new HashSet<AppLogDetail>();
    }

    public string AppLogDetailTypeCode {
      get;
      set;
    }
    public string AppLogDetailTypeDesc {
      get;
      set;
    }

    public virtual ICollection<AppLogDetail> AppLogDetails {
      get;
      set;
    }
  }
}
