//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "Account")]
  public partial class Account
  {
    public Account()
    {
      this.GroupMemberships = new HashSet<GroupMembership>();
      this.AccountLoginTokens = new HashSet<AccountLoginToken>();
      this.AppLogs = new HashSet<AppLog>();
      this.Orders = new HashSet<Order>();
      this.Referrals = new HashSet<Referral>();
    }

    public int AccountId {
      get;
      set;
    }
    public string AccountGuid {
      get;
      set;
    }
    public int AccountTypeId {
      get;
      set;
    }
    public string AccountName {
      get;
      set;
    }
    public int OrgId {
      get;
      set;
    }
    public int PersonId {
      get;
      set;
    }
    public string PasswordHash {
      get;
      set;
    }
    public string SecurityStamp {
      get;
      set;
    }
    public int AccountStatusId {
      get;
      set;
    }
    public int SecurityQuestionId {
      get;
      set;
    }
    public string SecurityAnswer {
      get;
      set;
    }
    public int AccountPolicyId {
      get;
      set;
    }
    public Nullable<System.DateTime> LockoutEndDateUtc {
      get;
      set;
    }
    public int AccessFailedCount {
      get;
      set;
    }
    public System.DateTime CreatedDateTime {
      get;
      set;
    }
    public int CreatedAccountId {
      get;
      set;
    }
    public System.DateTime ModifiedDateTime {
      get;
      set;
    }
    public int ModifiedAccountId {
      get;
      set;
    }

    public virtual Account Account1 {
      get;
      set;
    }
    public virtual Account Account2 {
      get;
      set;
    }
    public virtual AccountPolicy AccountPolicy {
      get;
      set;
    }
    public virtual AccountStatu AccountStatu {
      get;
      set;
    }
    public virtual AccountType AccountType {
      get;
      set;
    }
    public virtual Person Person {
      get;
      set;
    }
    public virtual SecurityQuestion SecurityQuestion {
      get;
      set;
    }
    public virtual ICollection<GroupMembership> GroupMemberships {
      get;
      set;
    }
    public virtual ICollection<AccountLoginToken> AccountLoginTokens {
      get;
      set;
    }
    public virtual ICollection<AppLog> AppLogs {
      get;
      set;
    }
    public virtual ICollection<Order> Orders {
      get;
      set;
    }
    public virtual ICollection<Referral> Referrals {
      get;
      set;
    }
    public virtual Organization Organization {
      get;
      set;
    }
  }
}
