//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "C__MigrationHistory")]
  public partial class C__MigrationHistory
  {
    public string MigrationId {
      get;
      set;
    }
    public string ContextKey {
      get;
      set;
    }
    public byte[] Model {
      get;
      set;
    }
    public string ProductVersion {
      get;
      set;
    }
  }
}
