//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "Calendar")]
    public partial class Calendar
    {
        public int CalendarId { get; set; }
        public int CalendarYear { get; set; }
        public System.DateTime CalendarDate { get; set; }
        public int DateTypeID { get; set; }
        public string DateType { get; set; }
    }
}
