//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "Coupon")]
  public partial class Coupon
  {
    public int CouponId {
      get;
      set;
    }
    public string CouponTypeCode {
      get;
      set;
    }
    public string CouponDesc {
      get;
      set;
    }
    public double Discount {
      get;
      set;
    }

    public virtual CouponType CouponType {
      get;
      set;
    }
  }
}
