//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "FrameworkVersion")]
  public partial class FrameworkVersion
  {
    public int FrameworkVersionId {
      get;
      set;
    }
    public string FrameworkVersionString {
      get;
      set;
    }
    public string Version {
      get;
      set;
    }
    public string VersionNum {
      get;
      set;
    }
    public string ServicePackString {
      get;
      set;
    }
    public int StatusId {
      get;
      set;
    }

    public virtual Status Status {
      get;
      set;
    }
  }
}
