//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "Order")]
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Services = new HashSet<Service>();
        }
    
        public int OrderId { get; set; }
        public int AccountId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int StatusId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string IpAddress { get; set; }
        public string SessionId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Person Person { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Service> Services { get; set; }
    }
}
