//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "PersonStatu")]
    public partial class PersonStatu
    {
        public PersonStatu()
        {
            this.People = new HashSet<Person>();
        }
    
        public int PersonStatusId { get; set; }
        public string PersonStatusAbbr { get; set; }
        public string PersonStatus { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
    }
}
