//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "PhoneNumber")]
    public partial class PhoneNumber
    {
        public int PhoneNumberId { get; set; }
        public string PhoneNumberFormatCode { get; set; }
        public string PhoneNumberValue { get; set; }
    
        public virtual PhoneNumberFormat PhoneNumberFormat { get; set; }
    }
}
