//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "PrivacyStatu")]
    public partial class PrivacyStatu
    {
        public PrivacyStatu()
        {
            this.PersonAddresses = new HashSet<PersonAddress>();
            this.PersonEmailAddresses = new HashSet<PersonEmailAddress>();
            this.PersonPhoneNumbers = new HashSet<PersonPhoneNumber>();
        }
    
        public string PrivacyStatusCode { get; set; }
        public string PrivacyStatusDesc { get; set; }
    
        public virtual ICollection<PersonAddress> PersonAddresses { get; set; }
        public virtual ICollection<PersonEmailAddress> PersonEmailAddresses { get; set; }
        public virtual ICollection<PersonPhoneNumber> PersonPhoneNumbers { get; set; }
    }
}
