//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "Referral")]
  public partial class Referral
  {
    public int ReferralId {
      get;
      set;
    }
    public int AccountId {
      get;
      set;
    }
    public string ReferralTypeCode {
      get;
      set;
    }
    public string ReferralCode {
      get;
      set;
    }
    public int StatusId {
      get;
      set;
    }
    public int CouponId {
      get;
      set;
    }
    public double Commission {
      get;
      set;
    }

    public virtual Account Account {
      get;
      set;
    }
    public virtual ReferralType ReferralType {
      get;
      set;
    }
    public virtual Status Status {
      get;
      set;
    }
  }
}
