//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "RelatedPerson")]
    public partial class RelatedPerson
    {
        public int PersonId { get; set; }
        public int RelatedPersonId { get; set; }
        public string RelationshipTypeCode { get; set; }
        public Nullable<System.DateTime> RelationshipBeginDateTime { get; set; }
        public Nullable<System.DateTime> RelationshipEndDateTime { get; set; }
        public int StatusId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual RelationshipType RelationshipType { get; set; }
    }
}
