//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "SecurityQuestion")]
    public partial class SecurityQuestion
    {
        public SecurityQuestion()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int SecurityQuestionId { get; set; }
        public string SecurityQuestionText { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> Sequencer { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Status Status { get; set; }
    }
}
