//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "Status")]
    public partial class Status
    {
        public Status()
        {
            this.ConfigItems = new HashSet<ConfigItem>();
            this.Groups = new HashSet<Group>();
            this.GroupMemberships = new HashSet<GroupMembership>();
            this.Orders = new HashSet<Order>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.PasswordChangeHistories = new HashSet<PasswordChangeHistory>();
            this.PersonAddresses = new HashSet<PersonAddress>();
            this.PersonPhoneNumbers = new HashSet<PersonPhoneNumber>();
            this.PoliticalUnits = new HashSet<PoliticalUnit>();
            this.Products = new HashSet<Product>();
            this.Referrals = new HashSet<Referral>();
            this.SecurityQuestions = new HashSet<SecurityQuestion>();
            this.Services = new HashSet<Service>();
            this.SoftwareModules = new HashSet<SoftwareModule>();
            this.SoftwareRepositories = new HashSet<SoftwareRepository>();
            this.SoftwareVersions = new HashSet<SoftwareVersion>();
            this.StatusUsages = new HashSet<StatusUsage>();
            this.SoftwarePlatforms = new HashSet<SoftwarePlatform>();
            this.FrameworkVersions = new HashSet<FrameworkVersion>();
        }
    
        public int StatusId { get; set; }
        public string StatusValue { get; set; }
    
        public virtual ICollection<ConfigItem> ConfigItems { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<GroupMembership> GroupMemberships { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<PasswordChangeHistory> PasswordChangeHistories { get; set; }
        public virtual ICollection<PersonAddress> PersonAddresses { get; set; }
        public virtual ICollection<PersonPhoneNumber> PersonPhoneNumbers { get; set; }
        public virtual ICollection<PoliticalUnit> PoliticalUnits { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Referral> Referrals { get; set; }
        public virtual ICollection<SecurityQuestion> SecurityQuestions { get; set; }
        public virtual ICollection<Service> Services { get; set; }
        public virtual ICollection<SoftwareModule> SoftwareModules { get; set; }
        public virtual ICollection<SoftwareRepository> SoftwareRepositories { get; set; }
        public virtual ICollection<SoftwareVersion> SoftwareVersions { get; set; }
        public virtual ICollection<StatusUsage> StatusUsages { get; set; }
        public virtual ICollection<SoftwarePlatform> SoftwarePlatforms { get; set; }
        public virtual ICollection<FrameworkVersion> FrameworkVersions { get; set; }
    }
}
