//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "TaskScheduleElement")]
  public partial class TaskScheduleElement
  {
    public int TaskScheduleElementId {
      get;
      set;
    }
    public int TaskScheduleId {
      get;
      set;
    }
    public bool IsActive {
      get;
      set;
    }
    public bool IsManaged {
      get;
      set;
    }
    public Nullable<int> ElementNumber {
      get;
      set;
    }
    public int TaskScheduleExecutionTypeId {
      get;
      set;
    }
    public Nullable<decimal> FrequencySeconds {
      get;
      set;
    }
    public bool IsClockAligned {
      get;
      set;
    }
    public Nullable<int> ScheduleElementPriority {
      get;
      set;
    }
    public Nullable<System.DateTime> StartDate {
      get;
      set;
    }
    public Nullable<System.TimeSpan> StartTime {
      get;
      set;
    }
    public Nullable<System.DateTime> EndDate {
      get;
      set;
    }
    public Nullable<System.TimeSpan> EndTime {
      get;
      set;
    }
    public Nullable<int> IntervalTypeId {
      get;
      set;
    }
    public bool OnSunday {
      get;
      set;
    }
    public bool OnMonday {
      get;
      set;
    }
    public bool OnTuesday {
      get;
      set;
    }
    public bool OnWednesday {
      get;
      set;
    }
    public bool OnThursday {
      get;
      set;
    }
    public bool OnFriday {
      get;
      set;
    }
    public bool OnSaturday {
      get;
      set;
    }
    public bool OnWorkDays {
      get;
      set;
    }
    public bool OnEvenDays {
      get;
      set;
    }
    public bool OnOddDays {
      get;
      set;
    }
    public string SpecificDays {
      get;
      set;
    }
    public bool ExceptSpecificDays {
      get;
      set;
    }
    public bool First {
      get;
      set;
    }
    public bool Second {
      get;
      set;
    }
    public bool Third {
      get;
      set;
    }
    public bool Fourth {
      get;
      set;
    }
    public bool Fifth {
      get;
      set;
    }
    public bool Last {
      get;
      set;
    }
    public bool Every {
      get;
      set;
    }
    public Nullable<int> HolidayActionId {
      get;
      set;
    }
    public Nullable<int> PeriodContextId {
      get;
      set;
    }
    public Nullable<int> ExecutionLimit {
      get;
      set;
    }
    public Nullable<int> MaxRunTimeSeconds {
      get;
      set;
    }
    public int CreatedBy {
      get;
      set;
    }
    public System.DateTime CreatedDate {
      get;
      set;
    }
    public int ModifiedBy {
      get;
      set;
    }
    public System.DateTime ModifiedDate {
      get;
      set;
    }

    public virtual HolidayAction HolidayAction {
      get;
      set;
    }
    public virtual PeriodContext PeriodContext {
      get;
      set;
    }
    public virtual TaskSchedule TaskSchedule {
      get;
      set;
    }
    public virtual TaskScheduleExecutionType TaskScheduleExecutionType {
      get;
      set;
    }
    public virtual TaskScheduleIntervalType TaskScheduleIntervalType {
      get;
      set;
    }
  }
}
