//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.DB;
using Org.GS;
namespace Org.AdsdiOrg.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "TriviaOption")]
  public partial class TriviaOption
  {
    public int QuestionId {
      get;
      set;
    }
    public int Id {
      get;
      set;
    }
    public string Title {
      get;
      set;
    }
    public bool IsCorrect {
      get;
      set;
    }
  }
}
