//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.CTL {
  using System;


  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class ButtonBarResources {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal ButtonBarResources() {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Org.CTL.ButtonBarResources", typeof(ButtonBarResources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap button1 {
      get {
        object obj = ResourceManager.GetObject("button1", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ClearLog {
      get {
        object obj = ResourceManager.GetObject("ClearLog", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Commit {
      get {
        object obj = ResourceManager.GetObject("Commit", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Hide {
      get {
        object obj = ResourceManager.GetObject("Hide", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Pause {
      get {
        object obj = ResourceManager.GetObject("Pause", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Resume {
      get {
        object obj = ResourceManager.GetObject("Resume", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap ShowLog {
      get {
        object obj = ResourceManager.GetObject("ShowLog", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Start {
      get {
        object obj = ResourceManager.GetObject("Start", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Stop {
      get {
        object obj = ResourceManager.GetObject("Stop", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap SvnStop {
      get {
        object obj = ResourceManager.GetObject("SvnStop", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap SyncLeft {
      get {
        object obj = ResourceManager.GetObject("SyncLeft", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap SyncRight {
      get {
        object obj = ResourceManager.GetObject("SyncRight", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type System.Drawing.Bitmap.
    /// </summary>
    internal static System.Drawing.Bitmap Update {
      get {
        object obj = ResourceManager.GetObject("Update", resourceCulture);
        return ((System.Drawing.Bitmap)(obj));
      }
    }
  }
}
