//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "AccountStatu")]
  public partial class AccountStatu
  {
    public AccountStatu()
    {
      this.Accounts = new HashSet<Account>();
    }

    public int AccountStatusId {
      get;
      set;
    }
    public string AccountStatus {
      get;
      set;
    }

    public virtual ICollection<Account> Accounts {
      get;
      set;
    }
  }
}
