//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "AccountLoginToken")]
    public partial class AccountLoginToken
    {
        public long AccountLoginTokenId { get; set; }
        public int AccountId { get; set; }
        public string Token { get; set; }
        public System.DateTime TokenCreateDateTime { get; set; }
        public System.DateTime TokenExpireDateTime { get; set; }
        public int TokenStatusId { get; set; }
        public string IpAddress { get; set; }
        public int TimesUsed { get; set; }
        public string ClientHash { get; set; }
        public Nullable<System.DateTime> LoggedOutDateTime { get; set; }
    
        public virtual AccountTokenStatu AccountTokenStatu { get; set; }
        public virtual Account Account { get; set; }
    }
}
