//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "AppLogEntity")]
  public partial class AppLogEntity
  {
    public AppLogEntity()
    {
      this.AppLogs = new HashSet<AppLog>();
    }

    public int EntityTypeId {
      get;
      set;
    }
    public string Name {
      get;
      set;
    }

    public virtual ICollection<AppLog> AppLogs {
      get;
      set;
    }
  }
}
