//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "CouponType")]
    public partial class CouponType
    {
        public CouponType()
        {
            this.Coupons = new HashSet<Coupon>();
        }
    
        public string CouponTypeCode { get; set; }
        public string CouponTypeDesc { get; set; }
    
        public virtual ICollection<Coupon> Coupons { get; set; }
    }
}
