//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "EmailAddressType")]
    public partial class EmailAddressType
    {
        public EmailAddressType()
        {
            this.PersonEmailAddresses = new HashSet<PersonEmailAddress>();
        }
    
        public string EmailAddressTypeCode { get; set; }
        public string EmailAddressTypeValue { get; set; }
        public string EmailAddressTypeDesc { get; set; }
    
        public virtual ICollection<PersonEmailAddress> PersonEmailAddresses { get; set; }
    }
}
