//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "OrgPerson")]
    public partial class OrgPerson
    {
        public int OrgPersonId { get; set; }
        public int OrgId { get; set; }
        public int PersonId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Person Person { get; set; }
    }
}
