//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "Person")]
    public partial class Person
    {
        public Person()
        {
            this.Orders = new HashSet<Order>();
            this.OrgPersons = new HashSet<OrgPerson>();
            this.PersonEmailAddresses = new HashSet<PersonEmailAddress>();
            this.RelatedPersons = new HashSet<RelatedPerson>();
            this.RelatedPersons1 = new HashSet<RelatedPerson>();
        }
    
        public int PersonId { get; set; }
        public int AccountId { get; set; }
        public bool AccountOwner { get; set; }
        public int PersonStatusId { get; set; }
        public string Salutation { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int CreatedAccountId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public Nullable<int> ModifiedAccountId { get; set; }
        public bool IsInitial { get; set; }
        public string CustomName { get; set; }
        public bool UseCustomName { get; set; }
        public int NameFormatId { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<OrgPerson> OrgPersons { get; set; }
        public virtual ICollection<PersonEmailAddress> PersonEmailAddresses { get; set; }
        public virtual ICollection<RelatedPerson> RelatedPersons { get; set; }
        public virtual ICollection<RelatedPerson> RelatedPersons1 { get; set; }
        public virtual Account Account { get; set; }
    }
}
