//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "PhoneNumberFormat")]
  public partial class PhoneNumberFormat
  {
    public PhoneNumberFormat()
    {
      this.PhoneNumbers = new HashSet<PhoneNumber>();
    }

    public string PhoneNumberFormatCode {
      get;
      set;
    }
    public string PhoneNumberFormatDesc {
      get;
      set;
    }

    public virtual ICollection<PhoneNumber> PhoneNumbers {
      get;
      set;
    }
  }
}
