//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "ProductCategory")]
  public partial class ProductCategory
  {
    public ProductCategory()
    {
      this.Products = new HashSet<Product>();
    }

    public string ProductCategoryCode {
      get;
      set;
    }
    public string ProductCategoryDesc {
      get;
      set;
    }

    public virtual ICollection<Product> Products {
      get;
      set;
    }
  }
}
