//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "ResumeStatu")]
    public partial class ResumeStatu
    {
        public ResumeStatu()
        {
            this.Resumes = new HashSet<Resume>();
        }
    
        public int ResumeStatusId { get; set; }
        public string ResumeStatusDesc { get; set; }
    
        public virtual ICollection<Resume> Resumes { get; set; }
    }
}
