//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
  using System;
  using System.Collections.Generic;

  [DbMap(DbElement.Table, "Adsdi_Org", "", "SoftwarePlatform")]
  public partial class SoftwarePlatform
  {
    public SoftwarePlatform()
    {
      this.SoftwareVersions = new HashSet<SoftwareVersion>();
    }

    public int SoftwarePlatformId {
      get;
      set;
    }
    public string SoftwarePlatformString {
      get;
      set;
    }
    public string PlatformDescription {
      get;
      set;
    }
    public int StatusId {
      get;
      set;
    }

    public virtual Status Status {
      get;
      set;
    }
    public virtual ICollection<SoftwareVersion> SoftwareVersions {
      get;
      set;
    }
  }
}
