//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Org.GS;
using Org.DB;
namespace Org.BMR.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    [DbMap(DbElement.Table, "Adsdi_Org", "", "TestTable1")]
    public partial class TestTable1
    {
        public int int_pk { get; set; }
        public Nullable<long> bigint_n { get; set; }
        public long bigint_nn { get; set; }
        public byte[] binary_1000_n { get; set; }
        public byte[] binary_1000_nn { get; set; }
        public Nullable<bool> bit_n { get; set; }
        public bool bit_nn { get; set; }
        public string char_20_n { get; set; }
        public string char_20_nn { get; set; }
        public Nullable<System.DateTime> date_n { get; set; }
        public System.DateTime date_nn { get; set; }
        public Nullable<System.DateTime> datetime_n { get; set; }
        public System.DateTime datetime_nn { get; set; }
        public Nullable<System.DateTime> datetime2_7_n { get; set; }
        public System.DateTime datetime2_7_nn { get; set; }
        public Nullable<System.DateTimeOffset> datetimeoffset_7_n { get; set; }
        public System.DateTimeOffset datetimeoffset_7_nn { get; set; }
        public Nullable<decimal> decimal18_0_n { get; set; }
        public decimal decimal18_0_nn { get; set; }
        public Nullable<decimal> decimal18_2_n { get; set; }
        public decimal decimal18_2_nn { get; set; }
        public Nullable<double> float_n { get; set; }
        public double float_nn { get; set; }
        public byte[] image_n { get; set; }
        public byte[] image_nn { get; set; }
        public Nullable<int> int_n { get; set; }
        public int int_nn { get; set; }
        public Nullable<decimal> money_n { get; set; }
        public decimal money_nn { get; set; }
        public string nchar_20_n { get; set; }
        public string nchar_20_nn { get; set; }
        public string ntext_n { get; set; }
        public string ntext_nn { get; set; }
        public Nullable<decimal> numeric_18_0_n { get; set; }
        public decimal numeric_18_0_nn { get; set; }
        public Nullable<decimal> numeric_18_2_n { get; set; }
        public decimal numeric_18_2_nn { get; set; }
        public string nvarchar_50_n { get; set; }
        public string nvarchar_50_nn { get; set; }
        public Nullable<float> real_n { get; set; }
        public float real_nn { get; set; }
        public Nullable<System.DateTime> smalldatetime_n { get; set; }
        public System.DateTime smalldatetime_nn { get; set; }
        public Nullable<short> smallint_n { get; set; }
        public short smallint_nn { get; set; }
        public Nullable<decimal> smallmoney_n { get; set; }
        public decimal smallmoney_nn { get; set; }
        public string text_n { get; set; }
        public string text_nn { get; set; }
        public Nullable<System.TimeSpan> time_7_n { get; set; }
        public System.TimeSpan time_7_nn { get; set; }
        public Nullable<byte> tinyint_n { get; set; }
        public byte tinyint_nn { get; set; }
        public Nullable<System.Guid> uniqueidentifier_n { get; set; }
        public System.Guid uniqueidentifier_nn { get; set; }
        public byte[] varbinary_1000_n { get; set; }
        public byte[] varbinary_1000_nn { get; set; }
        public string varchar_50_n { get; set; }
        public string varchar_50_nn { get; set; }
        public string xml_n { get; set; }
        public string xml_nn { get; set; }
    }
}
