//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.GS {
  using System;


  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Resource1 {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resource1() {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Org.GS.Resource1", typeof(Resource1).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to ÎV![nG)SVjZ4?G^uÔ|$@2x&amp;_K®}$AJn46[yël$lGl_jQ;]¨,%#r_ARKo»P&amp;w%l(5B*ç&amp;@1qaw@}UKorÐd[ç;[(0yqAog_5xflL¸f[(Q³n]?·b_++H6g_7[Q^Pt}g70Ó.{fPenXWGxI¶C+HuR&gt;z$?p&gt;_6&amp;Õ&lt;+qoF$z­(=?m&gt;ì-&gt;+_tVSvVqª:2a#L&lt;a:2&amp;#Yu?Ø?3_&gt;FfjB##ð{4?&amp;n+hçj55IwBKmµz7e)&amp;&lt;è)cUR]A¨YD@hwT6R$vJ&gt;)vux^gÍFe)t#1?9¶$FB%=Ij=c+è@fG(&gt;gKr*&amp;;è!h?+&amp;:dÆMHR!r1H3a#9T(%[³^hs:rNH?:A(^W7ìSi@$E)FqvI#0¾=j^nr!=tÏxJ&lt;V¹rj9rNZpësjVv&gt;?c(ë+k{[&gt;rr}Í#KN%Z&gt;Sh(Õ%LS(TtOXHE_®JqRc*l$e5S+5ÍuQxqp^C+^KÉpTdt&amp;»vU&gt;%*=X&amp;14eÚ]V8Oi^&gt;&amp;^1j?+Õ*xOeU0Yð&gt;Y=+^C6gyÍ_Y6QCS=@qI;FRBZÛhyZ=h4î[z$JNat1}Dx.
    /// </summary>
    internal static string obky {
      get {
        return ResourceManager.GetString("obky", resourceCulture);
      }
    }
  }
}
